<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <OutputType>Exe</OutputType>
    <PackageId>TtWork.Project.Migrator</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TtWork.Project.Core\TtWork.Project.Core.csproj" />
    <ProjectReference
      Include="..\TtWork.Project.EntityFrameworkCore\TtWork.Project.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\Modules\TtWork.Abp.Core\TtWork.Abp.Core.csproj" />
  </ItemGroup>
</Project>