<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <LangVersion>default</LangVersion>
        <RootNamespace>TtWork.Project</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2"/>

        <!--        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />-->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2"/>
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2"/>
        <!--        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />-->
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\FreeIM\FreeIM\FreeIM.csproj"/>
        <ProjectReference Include="..\..\Modules\TtWork.Abp.AppManagement\TtWork.Abp.AppManagement.csproj"/>
        <ProjectReference Include="..\TtWork.Project.Core\TtWork.Project.Core.csproj"/>
        <ProjectReference Include="..\TtWork.Project\TtWork.Project.csproj" />
    </ItemGroup>
</Project>