#!/bin/bash
# Fastlane Match 快速配置脚本
# 用于交互式配置 Apple Developer 信息

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(dirname "$SCRIPT_DIR")"

echo "=========================================="
echo "  Fastlane Match 配置向导"
echo "=========================================="
echo ""

# 检查 fastlane 是否安装
if ! command -v fastlane &> /dev/null; then
    echo "❌ Fastlane 未安装"
    echo "请运行: brew install fastlane"
    exit 1
fi

echo "✅ Fastlane 已安装: $(fastlane --version)"
echo ""

# 收集用户信息
echo "📝 请输入以下信息："
echo ""

# Apple ID
read -p "Apple ID (邮箱): " APPLE_ID
if [ -z "$APPLE_ID" ]; then
    echo "❌ Apple ID 不能为空"
    exit 1
fi

# Team ID
echo ""
echo "💡 Team ID 查找方法:"
echo "   1. 访问 https://developer.apple.com/account"
echo "   2. 点击 Account → Membership"
echo "   3. 查看 Team ID (10位字符)"
echo ""
read -p "Team ID (10位字符): " TEAM_ID
if [ -z "$TEAM_ID" ] || [ ${#TEAM_ID} -ne 10 ]; then
    echo "❌ Team ID 必须是10位字符"
    exit 1
fi

# Git 仓库地址
echo ""
echo "💡 证书存储 Git 仓库:"
echo "   - 建议创建新的 Private GitHub 仓库"
echo "   - 仓库名建议: molitao-ios-certs"
echo "   - ⚠️ 必须设置为 Private"
echo ""
read -p "Git 仓库地址 (例如 git@github.com:user/molitao-certs.git): " GIT_URL
if [ -z "$GIT_URL" ]; then
    echo "❌ Git 仓库地址不能为空"
    exit 1
fi

# Match 密码
echo ""
echo "💡 Match 密码用于加密证书，请妥善保管！"
echo "   - 至少12个字符"
echo "   - 包含大小写字母、数字、特殊符号"
echo ""
read -s -p "Match 密码 (输入后回车，不显示): " MATCH_PASSWORD
echo ""
if [ -z "$MATCH_PASSWORD" ] || [ ${#MATCH_PASSWORD} -lt 12 ]; then
    echo "❌ Match 密码至少需要12个字符"
    exit 1
fi

# 确认信息
echo ""
echo "=========================================="
echo "  配置信息确认"
echo "=========================================="
echo "Apple ID:    $APPLE_ID"
echo "Team ID:     $TEAM_ID"
echo "Git URL:     $GIT_URL"
echo "密码长度:    ${#MATCH_PASSWORD} 字符"
echo ""
read -p "确认以上信息正确? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "❌ 已取消"
    exit 1
fi

# 更新 Appfile
echo ""
echo "📝 更新 Appfile..."
cat > "$SCRIPT_DIR/Appfile" << EOF
# App configuration for molitao_app
# Auto-generated by setup.sh

apple_id("$APPLE_ID")
team_id("$TEAM_ID")
bundle_identifier("com.molitao.molitaoApp")
app_name("魔力淘")
itc_team_id("$TEAM_ID")
EOF
echo "✅ Appfile 已更新"

# 更新 Matchfile
echo "📝 更新 Matchfile..."
cat > "$SCRIPT_DIR/Matchfile" << EOF
# Matchfile for molitao_app iOS
# Auto-generated by setup.sh

git_url("$GIT_URL")
git_branch("master")
storage_mode("git")
type("appstore")
app_identifier(["com.molitao.molitaoApp"])
team_id("$TEAM_ID")
username("$APPLE_ID")
force_for_new_devices(true)
readonly(true)
EOF
echo "✅ Matchfile 已更新"

# 设置环境变量
echo "📝 设置 MATCH_PASSWORD 环境变量..."
if [ -f ~/.zshrc ]; then
    # 检查是否已存在
    if grep -q "MATCH_PASSWORD" ~/.zshrc 2>/dev/null; then
        echo "⚠️  MATCH_PASSWORD 已在 ~/.zshrc 中定义，请手动更新"
    else
        echo "" >> ~/.zshrc
        echo "# Fastlane Match Password" >> ~/.zshrc
        echo "export MATCH_PASSWORD=\"$MATCH_PASSWORD\"" >> ~/.zshrc
        echo "✅ 已添加到 ~/.zshrc"
    fi
elif [ -f ~/.bash_profile ]; then
    if grep -q "MATCH_PASSWORD" ~/.bash_profile 2>/dev/null; then
        echo "⚠️  MATCH_PASSWORD 已在 ~/.bash_profile 中定义，请手动更新"
    else
        echo "" >> ~/.bash_profile
        echo "# Fastlane Match Password" >> ~/.bash_profile
        echo "export MATCH_PASSWORD=\"$MATCH_PASSWORD\"" >> ~/.bash_profile
        echo "✅ 已添加到 ~/.bash_profile"
    fi
else
    echo "⚠️  未找到 shell 配置文件，请手动设置环境变量:"
    echo "   export MATCH_PASSWORD=\"$MATCH_PASSWORD\""
fi

# 创建 .gitignore
echo "📝 创建 .gitignore..."
cat > "$IOS_DIR/.gitignore" << 'EOF'
# Fastlane
fastlane/report.xml
fastlane/.fastlane.yml
fastlane/AuthKey_*.p8
fastlane/.env
fastlane/.env.default

# Build
*.ipa
*.dSYM.zip
build/
DerivedData/

# CocoaPods (if used)
Pods/

# Carthage (if used)
Carthage/Build/
EOF
echo "✅ .gitignore 已创建"

# 完成
echo ""
echo "=========================================="
echo "  ✅ 配置完成！"
echo "=========================================="
echo ""
echo "📋 下一步操作:"
echo ""
echo "1. 确保 Git 仓库已创建:"
echo "   $GIT_URL"
echo ""
echo "2. 重新加载 shell 配置:"
echo "   source ~/.zshrc  # 或 source ~/.bash_profile"
echo ""
echo "3. 创建证书 (首次):"
echo "   cd $IOS_DIR"
echo "   fastlane create_appstore_cert"
echo ""
echo "4. 后续同步证书:"
echo "   fastlane sync_appstore_certs"
echo ""
echo "📚 详细文档: $SCRIPT_DIR/SETUP_GUIDE.md"
echo ""
