<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TtWork.Abp.Core\TtWork.Abp.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

</Project>
