<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TtWork.Project\TtWork.Project.csproj" />
    <ProjectReference Include="..\..\src\TtWork.Project.EntityFrameworkCore\TtWork.Project.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\TtWork.Project.Core\TtWork.Project.Core.csproj" />
    <ProjectReference Include="..\..\Modules\TtWork.Abp.Core\TtWork.Abp.Core.csproj" />
    <ProjectReference Include="..\..\Modules\TtWork.Abp.AppManagement\TtWork.Abp.AppManagement.csproj" />
    <ProjectReference Include="..\..\Modules\TtWork.Abp.Entity\TtWork.Abp.Entity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.33" />
  </ItemGroup>
</Project>
