/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMsgConfiguration: typeof import('./src/components/Chat/addMsgConfiguration.vue')['default']
    AnnounceDialog: typeof import('./src/components/Chat/announceDialog.vue')['default']
    AnnounceDiv: typeof import('./src/components/Chat/announceDiv.vue')['default']
    AnnounceQueryFilter: typeof import('./src/components/paged-table/announceQueryFilter.vue')['default']
    AuctionBidMessage: typeof import('./src/components/Chat/AuctionBidMessage.vue')['default']
    AuctionDealMessage: typeof import('./src/components/Chat/AuctionDealMessage.vue')['default']
    AuctionEndMessage: typeof import('./src/components/Chat/AuctionEndMessage.vue')['default']
    AuctionItemDetail: typeof import('./src/components/Chat/auctionItemDetail.vue')['default']
    AuctionItemQueryFilter: typeof import('./src/components/paged-table/auctionItemQueryFilter.vue')['default']
    AuctionList: typeof import('./src/components/Chat/AuctionList.vue')['default']
    AuctionStartMessage: typeof import('./src/components/Chat/AuctionStartMessage.vue')['default']
    AuditQueryFilter: typeof import('./src/components/paged-table/auditQueryFilter.vue')['default']
    ChatInput: typeof import('./src/components/Chat/ChatInput.vue')['default']
    ChatMain: typeof import('./src/components/Chat/chatMain.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/index.vue')['default']
    CreateGroupDislog: typeof import('./src/components/Chat/createGroupDislog.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    EditAnnounce: typeof import('./src/components/Chat/editAnnounce.vue')['default']
    EditAuctionItem: typeof import('./src/components/Chat/editAuctionItem.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GroupList: typeof import('./src/components/Chat/GroupList.vue')['default']
    GroupSidePanel: typeof import('./src/components/Chat/GroupSidePanel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageMessage: typeof import('./src/components/Chat/ImageMessage.vue')['default']
    ListAuctionItem: typeof import('./src/components/Chat/listAuctionItem.vue')['default']
    MyButton: typeof import('./src/components/MyButton/index.vue')['default']
    NextButton: typeof import('./src/components/MyButton/NextButton.vue')['default']
    OrderQueryFilter: typeof import('./src/components/paged-table/orderQueryFilter.vue')['default']
    PagedTable: typeof import('./src/components/paged-table/index.vue')['default']
    QueryFilter: typeof import('./src/components/paged-table/queryFilter.vue')['default']
    RichTextDisplay: typeof import('./src/components/Chat/RichTextDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./src/components/paged-table/statusTag.vue')['default']
    TextMessage: typeof import('./src/components/Chat/TextMessage.vue')['default']
    TtUpload: typeof import('./src/components/tt-upload/index.vue')['default']
    UserInfoDialog: typeof import('./src/components/Chat/userInfoDialog.vue')['default']
    UserSetting: typeof import('./src/components/UserSetting.vue')['default']
    WithdrawalApprovaltem: typeof import('./src/components/Chat/withdrawalApprovaltem.vue')['default']
  }
}
