/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/announce/list" |
       "/pages/chat/auction" |
       "/pages/chat/contacts" |
       "/pages/chat/groupChat" |
       "/pages/chat/index" |
       "/pages/chat/lobby" |
       "/pages/chat/privateChat" |
       "/pages/index/login" |
       "/pages/index/my" |
       "/pages/tradingPost/index" |
       "/pages/tradingPost/postDetail" |
       "/pages/user/auctionSuccessList" |
       "/pages/user/balanceLog" |
       "/pages/user/depositLog" |
       "/pages/user/info" |
       "/pages/user/list";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/chat/index" | "/pages/chat/contacts" | "/pages/index/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
